import pathlib
from typing import Dict, List
from js import document, console

from metafor.core import ChildType, DOMNode
from metafor.transpiler import jsx_to_dom_func
from metafor.utils.html import html_sanitize

def load_css(css_path=''):
    css_file = pathlib.Path(css_path)
    assert (css_file).exists()

    css_content = load_css_as_docstring(css_path)
    return css_content
    
def load_css_as_docstring(file_path):
    with open(file_path, 'r') as file:
        css_content = file.read()
    
    # Return the content as a docstring (triple-quoted string)
    return f"""{css_content}"""

def add_scope_css(component_id, element, stylesheets):
  
    style_element = document.createElement("style")
    style_element.setAttribute(f"comp-id", component_id)
    
    # Combine all stylesheets and scope them to the component_id
    scoped_css = "\n".join([f"[comp-id='{component_id}'] {{ {css} }}" for css in stylesheets])
    style_element.textContent = scoped_css
    # Set the component_id as an attribute on the element
    element.setAttribute("comp-id", component_id)
    # Append the style element to the component
    element.prepend(style_element)

def add_global_css(component_id, stylesheets):
  
    style_element = document.createElement("style")
    style_element.setAttribute(f"comp-id", component_id)
    
    # Combine all stylesheets and scope them to the component_id
    style_content = "\n".join([f"{css} " for css in stylesheets])
    style_element.textContent = style_content
    
    # existing_styles = document.head.querySelectorAll('style[comp-id]')
    
    document.head.append(style_element)
        
def apply_css(component_id, element, stylesheets):
    if isinstance(stylesheets, str):
        stylesheets = [{'scoped': stylesheets}]

    if isinstance(stylesheets, dict):
        stylesheets = [stylesheets]

    for css in reversed(stylesheets):
        if "scoped" in css:
            add_scope_css(component_id, element, [css["scoped"]])
            
        if "global" in css:
            add_global_css(component_id, [css["global"]])


def sanitize_html(html_content):
    """
    Standalone function to sanitize HTML content
    """
    return html_sanitize(html_content)

def create_html_element(tag, props=None, html_content=None):
    """
    Create an element with sanitized HTML content
    """
    element = DOMNode(tag, props or {})
    if html_content is not None:
        element.set_html(html_content)
    return element

class DomBuilder:
    
    _page_title = None
    
    def __getattr__(self, name):
        def _tag(*children, **kwargs):
            return self.generate_tag(name, *children, **kwargs)
    
        return _tag
    
    def _jsx_parse(self, file_path, scope, css=None):
        # Get the caller's frame
        # If css is provided, we tell the transpiler to inject 'css' variable into the root element
        css_var_name = "css" if css is not None else None
        jsx_output = jsx_to_dom_func(file_path, scope, css_variable=css_var_name)
        
        # Import components locally to avoid circular dependency
        from metafor.components import Show, For, Switch, Match, Suspense, ErrorBoundary, Portal
        
        # Context for eval must include all components generated by transpiler
        eval_context = {
            't': t, 
            'Show': Show, 
            'For': For, 
            'Switch': Switch, 
            'Match': Match, 
            'Suspense': Suspense, 
            'ErrorBoundary': ErrorBoundary, 
            'Portal': Portal,
            **scope
        }
        
        if css is not None:
            eval_context['css'] = css

        output = eval(jsx_output, eval_context)
        return output
    
    def _update_document_title(self):
        if self._page_title:
            document.title = self._page_title
            self._page_title = None

    def jsx(self, file_path, context={}, css=None):
        if isinstance(file_path, str) and file_path.lower().endswith(".jsx"):
            return self._jsx_parse(file_path, context, css)        
    
    def page_title(self, title): 
        if self._page_title != title:
            self._page_title = title
    
    def generate_tag(self, tag: str, props: Dict = None, children: List[ChildType] = None, css=None, **kwargs):
        """
            Create a DOM element (similar to JSX/h function in SolidJS)
        """
        tag = tag.lower().strip()

        if kwargs.get("tag"):
            tag = kwargs.pop("tag")
        elif "_" in tag:
            tag = tag.replace("_", "-")

        namespace = kwargs.get("namespace")
        dom_node = DOMNode(tag, props, children, namespace=namespace)

        # Update document title
        self._update_document_title()

        # Add scoped styles if css are provided    
        if css:
            apply_css(id(dom_node), dom_node.element, css) 

        return dom_node

t = DomBuilder()